const LEGACY_KEY="simple-step-db";
const Data=window.SimpleStepData;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=Data.id,now=Data.now,dateKey=Data.dateKey;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let db=Data.createEmptyDatabase(),activeDate=dateKey(),calendarMonth=dateKey().slice(0,7),lastToday=dateKey();
const persist=()=>Data.repository.save(db),isLive=x=>!x.deletedAt,taskDate=t=>t.completedAt?.slice(0,10);
const itemOf=(kind,id)=>db[kind].find(x=>x.id===id);
const nameOf=(kind,id,includeDeleted=false)=>{const item=itemOf(kind,id);return item&&(includeDeleted||!item.deletedAt)?item.name:""};
const newestFirst=(a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||""));
const newest=items=>[...items].sort(newestFirst);
const currentDay=()=>Data.businessDateKey(db.settings),currentWeek=()=>Data.weekKey(currentDay(),db.settings.weekStartsOn),currentMonth=()=>Data.monthKey(currentDay());
const isThisWeek=t=>t.weekStatusKey===currentWeek(),isThisMonth=t=>t.monthStatusKey===currentMonth();

// Shared rendering helpers keep every task view tied to the same task record.
function approved(t){return isLive(t)&&t.approvalStatus!=="pending"}
function options(kind,selected=""){return '<option value="">指定なし</option>'+db[kind].filter(isLive).map(x=>`<option value="${x.id}" ${x.id===selected?"selected":""}>${esc(x.name)}</option>`).join("")}
function metaFor(t){return [nameOf("categories",t.categoryId),nameOf("projects",t.projectId),isThisWeek(t)?"今週":"",isThisMonth(t)?"今月":"",t.source==="ai"?"AI登録":""].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join("")}
function menuHtml(review=false){return `<div class="menu"><button class="more" data-action="menu" aria-label="操作">•••</button><div class="menu-panel" hidden><button data-action="edit-task">タスクカードを開く</button>${review?'<button data-action="change-date">完了日を直す</button>':""}<button class="danger" data-action="delete">削除する</button></div></div>`}
function taskHtml(t,{review=false,complete=false}={}){return `<article class="item" data-task-id="${t.id}">${complete?'<button class="complete" data-action="complete" title="完了">✓</button>':""}<div class="item-body"><p class="item-title">${esc(t.title)}</p><div class="meta">${metaFor(t)}</div></div>${menuHtml(review)}</article>`}
function journalHtml(j){const theme=nameOf("themes",j.themeId,true);return `<article class="item journal-item" data-journal-id="${j.id}"><div><div class="meta"><span>${esc(j.entryDate)}</span><span>${new Date(j.createdAt).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</span>${theme?`<span>テーマ：${esc(theme)}</span>`:""}</div><p class="journal-text">${esc(j.text)}</p></div><div class="menu"><button class="more" data-action="menu">•••</button><div class="menu-panel" hidden><button class="danger" data-action="delete-journal">削除する</button></div></div></article>`}
function taskActions(task){return `<div class="button-row"><button class="period-check ${isThisWeek(task)?"active":""}" data-action="star" data-period="week" title="今週">W</button><button class="period-check ${isThisMonth(task)?"active":""}" data-action="star" data-period="month" title="今月">M</button><button class="star ${task.todayDate===currentDay()?"active":""}" data-action="star" data-period="today" title="今日">${task.todayDate===currentDay()?"★":"☆"}</button>${menuHtml()}</div>`}
function openTaskRow(t){return `<article class="item" data-task-id="${t.id}"><button class="complete" data-action="complete" title="完了">✓</button><div class="item-body"><button class="task-title-button" data-action="edit-task">${esc(t.title)}</button><div class="meta">${metaFor(t)}</div></div>${taskActions(t)}</article>`}
function renderTasks(){const today=currentDay(),open=newest(db.tasks.filter(t=>approved(t)&&t.status!=="done")),starred=open.filter(t=>t.todayDate===today),backlog=open.filter(t=>t.todayDate!==today);$("#todayLabel").textContent=new Date(today+"T12:00:00").toLocaleDateString("ja-JP",{month:"long",day:"numeric",weekday:"short"});$("#todayCount").textContent=starred.length+"件";$("#backlogCount").textContent=backlog.length+"件";$("#todayTasks").innerHTML=starred.length?starred.map(openTaskRow).join(""):"<div class='empty'>星を付けたタスクが、ここに並びます。</div>";$("#backlogTasks").innerHTML=backlog.length?backlog.map(openTaskRow).join(""):"<div class='empty'>次にやることはありません。</div>"}
function renderPeriodTasks(){const open=newest(db.tasks.filter(t=>approved(t)&&t.status!=="done")),week=open.filter(isThisWeek),month=open.filter(isThisMonth),start=new Date(currentWeek()+"T12:00:00"),end=new Date(start);end.setDate(end.getDate()+6);$("#weekRange").textContent=`${start.toLocaleDateString("ja-JP",{month:"numeric",day:"numeric"})}～${end.toLocaleDateString("ja-JP",{month:"numeric",day:"numeric"})}`;$("#monthLabel").textContent=currentMonth().replace("-","年")+"月";$("#weekTaskList").innerHTML=week.length?week.map(openTaskRow).join(""):"<div class='empty'>今週のタスクはありません。</div>";$("#monthTaskList").innerHTML=month.length?month.map(openTaskRow).join(""):"<div class='empty'>今月のタスクはありません。</div>"}

// Page renderers read from db only; persistence stays in event and bridge handlers.
function renderJournals(){const selected=$("#journalDate").value||dateKey(),done=db.tasks.filter(t=>approved(t)&&t.status==="done"&&taskDate(t)===selected),rows=db.journals.filter(isLive).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,50),themes=db.themes.filter(t=>isLive(t)&&t.active);$("#journalDoneCount").textContent=done.length+"件";$("#journalDoneTasks").innerHTML=done.length?done.map(t=>taskHtml(t)).join(""):"<div class='empty'>この日に完了したタスクはありません。</div>";$("#themeComposers").innerHTML=themes.length?themes.map(t=>`<form class="theme-composer card" data-theme-id="${t.id}"><label>${esc(t.name)}<textarea rows="2" maxlength="2000" required placeholder="${esc(t.name)}について今日の記録"></textarea></label><div class="form-footer"><small>任意</small><button class="secondary-button">記録</button></div></form>`).join(""):"<div class='empty'>継続テーマはプロジェクトタブから追加できます。</div>";$("#journalTimeline").innerHTML=rows.length?rows.map(journalHtml).join(""):"<div class='empty'>最初の日記を書いてみましょう。</div>"}
function renderCalendar(){const [y,m]=calendarMonth.split("-").map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),start=db.settings.weekStartsOn||0,names=["日","月","火","水","木","金","土"];$(".calendar-weekdays").innerHTML=Array.from({length:7},(_,i)=>`<span>${names[(start+i)%7]}</span>`).join("");$("#calendarTitle").textContent=`${y}年${m}月`;let html="";for(let i=0;i<(first.getDay()-start+7)%7;i++)html+='<span class="calendar-blank"></span>';for(let day=1;day<=days;day++){const key=`${calendarMonth}-${String(day).padStart(2,"0")}`,done=db.tasks.filter(t=>approved(t)&&t.status==="done"&&taskDate(t)===key).length,notes=db.journals.filter(j=>isLive(j)&&j.entryDate===key).length;html+=`<button class="calendar-day ${key===activeDate?"selected":""} ${key===currentDay()?"today":""}" data-date="${key}"><strong>${day}</strong><small>${done?"✓"+done:""} ${notes?"日"+notes:""}</small></button>`}$("#reviewCalendar").innerHTML=html}
function renderReview(){activeDate=$("#reviewDate").value||activeDate;$("#reviewDate").value=activeDate;calendarMonth=activeDate.slice(0,7);const selected=$("#reviewThemeFilter").value,current=selected;$("#reviewThemeFilter").innerHTML='<option value="">すべての日記</option><option value="__themed">テーマの記録だけ</option>'+db.themes.filter(isLive).map(t=>`<option value="${t.id}">${esc(t.name)}${t.active?"":"（終了）"}</option>`).join("");$("#reviewThemeFilter").value=current;const filter=$("#reviewThemeFilter").value,tasks=db.tasks.filter(t=>approved(t)&&t.status==="done"&&taskDate(t)===activeDate),journals=db.journals.filter(j=>isLive(j)&&j.entryDate===activeDate&&(!filter||(filter==="__themed"?Boolean(j.themeId):j.themeId===filter))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));renderCalendar();$("#reviewTasks").innerHTML=tasks.length?tasks.map(t=>taskHtml(t,{review:true})).join(""):"<div class='empty'>この日に完了したことはありません。</div>";$("#reviewJournals").innerHTML=journals.length?journals.map(journalHtml).join(""):"<div class='empty'>条件に合う日記はありません。</div>"}
function renderProjects(){for(const kind of ["categories","projects"]){const singular=kind==="categories"?"category":"project";$("#"+singular+"List").innerHTML=db[kind].filter(isLive).map(x=>`<span class="chip">${esc(x.name)}<button data-action="rename-class" data-kind="${kind}" data-id="${x.id}" title="名前を変更">✎</button><button data-action="delete-class" data-kind="${kind}" data-id="${x.id}" title="解除して削除">×</button></span>`).join("")||"<span class='meta'>まだありません</span>"}$("#themeList").innerHTML=db.themes.filter(isLive).map(t=>{const last=db.journals.filter(j=>isLive(j)&&j.themeId===t.id).sort((a,b)=>b.entryDate.localeCompare(a.entryDate))[0];return `<div class="theme-admin-row ${t.active?"":"ended"}"><div><strong>${esc(t.name)}</strong><small>${last?"最終記録 "+last.entryDate:"記録なし"}${t.active?"":"・終了中"}</small></div><div class="button-row"><button class="more" data-action="rename-theme" data-id="${t.id}">✎</button><button class="secondary-button" data-action="toggle-theme" data-id="${t.id}">${t.active?"終了":"再開"}</button></div></div>`}).join("")||"<div class='empty'>まだありません。</div>";const tasks=db.tasks.filter(t=>approved(t)&&t.status!=="done");$("#classificationCount").textContent=tasks.length+"件";$("#classificationTasks").innerHTML=tasks.length?tasks.map(t=>`<article class="classification-card card" data-task-id="${t.id}"><p class="item-title">${esc(t.title)}</p><div class="two-columns"><label>カテゴリ<select data-field="categoryId">${options("categories",t.categoryId)}</select></label><label>プロジェクト<select data-field="projectId">${options("projects",t.projectId)}</select></label></div></article>`).join(""):"<div class='empty'>整理する未完了タスクはありません。</div>"}
function renderRecurringRules(){const rows=db.recurringRules.filter(isLive);const labels={daily:"毎日",weekly:"毎週",monthly:"毎月",interval:"日ごと"};$("#recurringRuleList").innerHTML=rows.length?rows.map(rule=>{let schedule=labels[rule.frequency];if(rule.frequency==="weekly")schedule+=`（${rule.daysOfWeek.map(day=>"日月火水木金土"[day]).join("・")}）`;if(rule.frequency==="monthly")schedule+=` ${rule.dayOfMonth}日`;if(rule.frequency==="interval")schedule=`${rule.interval}日ごと`;return `<article class="item" data-rule-id="${rule.id}"><div class="item-body"><p class="item-title">${esc(rule.title)}</p><div class="meta"><span>${schedule}</span><span>${rule.startDate}から</span>${rule.active?"":"<span>停止中</span>"}</div></div><div class="button-row"><button class="more" data-action="edit-recurring">編集</button><button class="secondary-button" data-action="toggle-recurring">${rule.active?"停止":"再開"}</button></div></article>`}).join(""):"<div class='empty'>繰り返し設定はありません。</div>"}
function pendingTaskHtml(t){return `<article class="item" data-task-id="${t.id}"><div class="item-body"><p class="item-title">${esc(t.title)}</p><div class="meta"><span>新規タスク</span>${metaFor(t)}</div></div><div class="button-row"><button class="secondary-button" data-action="approve-pending">承認</button><button class="more danger" data-action="reject-pending">削除</button></div></article>`}
function changeValueLabel(field,value){if(field==="categoryId")return nameOf("categories",value)||"指定なし";if(field==="projectId")return nameOf("projects",value)||"指定なし";if(field==="priority")return ({none:"指定なし",low:"低",medium:"中",high:"高",urgent:"至急"})[value]||"指定なし";if(field==="estimateMinutes")return value?value+"分":"指定なし";if(["weekStatusKey","monthStatusKey"].includes(field))return value?"チェックあり":"チェックなし";return value||"指定なし"}
function pendingChangeHtml(c){const task=db.tasks.find(t=>t.id===c.taskId),labels={categoryId:"カテゴリ",projectId:"プロジェクト",description:"詳細",startDate:"とりかかり日",dueDate:"締め切り日",priority:"優先順位",estimateMinutes:"見積もり時間",weekStatusKey:"今週",monthStatusKey:"今月"},kind=labels[c.field]||c.field;return `<article class="item" data-change-id="${c.id}"><div class="item-body"><p class="item-title">${esc(task?.title||"対象タスクなし")}</p><div class="meta"><span>変更提案</span><span>${esc(kind)}：${esc(changeValueLabel(c.field,c.fromValue))} → ${esc(changeValueLabel(c.field,c.toValue))}</span></div></div><div class="button-row"><button class="secondary-button" data-action="approve-change">承認</button><button class="more danger" data-action="reject-change">削除</button></div></article>`}
function renderPending(){const tasks=db.tasks.filter(t=>isLive(t)&&t.approvalStatus==="pending"),changes=db.aiChanges.filter(c=>c.status==="pending");$("#inboxBadge").hidden=!(tasks.length+changes.length);$("#inboxBadge").textContent=tasks.length+changes.length;$("#approveAll").disabled=!(tasks.length+changes.length);$("#pendingItems").innerHTML=tasks.length+changes.length?[...tasks.map(pendingTaskHtml),...changes.map(pendingChangeHtml)].join(""):"<div class='empty'>未承認の項目はありません。</div>"}
function renderDeleted(){const rows=[...db.tasks.filter(x=>x.deletedAt).map(x=>({...x,kind:"task",label:x.title})),...db.journals.filter(x=>x.deletedAt).map(x=>({...x,kind:"journal",label:x.text}))].sort((a,b)=>b.deletedAt.localeCompare(a.deletedAt));$("#deletedItems").innerHTML=rows.length?rows.map(x=>`<article class="item" data-id="${x.id}" data-kind="${x.kind}"><div class="item-body"><p class="item-title">${esc(x.label)}</p><div class="meta"><span>${x.kind==="task"?"タスク":"日記"}</span></div></div><div class="button-row"><button class="secondary-button" data-action="restore">復元</button><button class="more danger" data-action="purge">完全削除</button></div></article>`).join(""):"<div class='empty'>削除済みの記録はありません。</div>"}
function renderSettings(){$("#weekStartsOn").value=String(db.settings.weekStartsOn);$("#dayRolloverTime").value=db.settings.dayRolloverTime}
function sortRecordsNewest(){for(const kind of ["tasks","journals","categories","projects","themes","recurringRules","aiChanges"]){db[kind].sort(newestFirst)}}
function moveTaskSaveButtonToTop(){const heading=$("#taskEditor .dialog-heading"),save=$("#saveTaskEditor"),close=heading?.querySelector('[value="cancel"]');if(heading&&save&&close&&save.parentElement!==heading)heading.insertBefore(save,close)}
function enhanceThemeDeletion(){for(const row of $$("#themeList .theme-admin-row")){const themeId=row.querySelector("[data-id]")?.dataset.id;if(!themeId||row.querySelector('[data-action="delete-theme"]'))continue;const button=document.createElement("button");button.type="button";button.className="more danger";button.dataset.action="delete-theme";button.dataset.id=themeId;button.textContent="削除";row.querySelector(".button-row")?.append(button)}}
function includeDeletedThemesInReview(){const select=$("#reviewThemeFilter"),used=new Set(db.journals.filter(isLive).map(j=>j.themeId).filter(Boolean));for(const theme of newest(db.themes.filter(t=>t.deletedAt&&used.has(t.id)))){if(select.querySelector(`option[value="${theme.id}"]`))continue;const option=document.createElement("option");option.value=theme.id;option.textContent=theme.name+"（削除済み）";select.append(option)}}
function renderAll(){sortRecordsNewest();moveTaskSaveButtonToTop();renderTasks();renderPeriodTasks();renderJournals();renderReview();includeDeletedThemesInReview();renderProjects();enhanceThemeDeletion();renderRecurringRules();renderPending();renderDeleted();renderSettings()}
async function addTask(value,source="manual",approvalStatus="approved",requestId=""){if(requestId&&db.importHistory.some(x=>x.requestId===requestId))return null;const task=Data.createTask({...value,source,approvalStatus,requestId,updatedBy:source==="ai"?"ai":"user"});db.tasks.push(task);if(requestId)db.importHistory.push({requestId,receivedAt:now()});await persist();return task}
async function actTask(target,action){const row=target.closest("[data-task-id]"),task=db.tasks.find(x=>x.id===row?.dataset.taskId);if(!task)return;const changes={},period=target.dataset.period;if(action==="star"&&period==="today")changes.todayDate=task.todayDate===currentDay()?null:currentDay();if(action==="star"&&period==="week")changes.weekStatusKey=isThisWeek(task)?null:currentWeek();if(action==="star"&&period==="month")changes.monthStatusKey=isThisMonth(task)?null:currentMonth();if(action==="complete")Object.assign(changes,{status:"done",completedAt:now(),todayDate:null});if(action==="delete")changes.deletedAt=now();if(action==="change-date"){const value=prompt("正しい完了日（YYYY-MM-DD）",taskDate(task));if(value&&/^\d{4}-\d{2}-\d{2}$/.test(value))changes.completedAt=value+"T12:00:00.000Z"}Data.updateTask(task,changes,"user");await persist();renderAll()}
function ensureName(kind,name){if(!name)return"";let item=db[kind].find(x=>isLive(x)&&x.name.toLowerCase()===name.trim().toLowerCase());if(!item){item={id:uid(),name:name.trim(),createdAt:now(),deletedAt:null};db[kind].push(item)}return item.id}
async function receiveAITasks(payload){const values=Array.isArray(payload)?payload:payload.tasks||[];let added=0;for(const [i,v] of values.entries()){if(!v.title?.trim())continue;const requestId=v.requestId||payload.requestId&&`${payload.requestId}:${i}`||"";const task=await addTask({title:v.title,description:v.description||"",categoryId:ensureName("categories",v.category),projectId:ensureName("projects",v.project),startDate:v.startDate||null,dueDate:v.dueDate||null,priority:v.priority||"none",estimateMinutes:Number.isInteger(v.estimateMinutes)?v.estimateMinutes:null,weekStatusKey:v.weekStatus?currentWeek():null,monthStatusKey:v.monthStatus?currentMonth():null},"ai","pending",requestId);if(task)added++}await persist();renderAll();return {received:added}}
async function receiveAIChanges(payload){const allowed=["categoryId","projectId","description","startDate","dueDate","priority","estimateMinutes","weekStatus","monthStatus"],changes=Array.isArray(payload)?payload:payload.changes||[];let added=0;for(const [i,v] of changes.entries()){const task=db.tasks.find(t=>t.id===v.taskId&&approved(t));if(!task||!allowed.includes(v.field))continue;const requestId=v.requestId||(!Array.isArray(payload)&&payload.requestId?`${payload.requestId}:${i}`:"");if(requestId&&db.importHistory.some(x=>x.requestId===requestId))continue;const requested=v.value??v.valueId??null,field=v.field==="weekStatus"?"weekStatusKey":v.field==="monthStatus"?"monthStatusKey":v.field,toValue=v.field==="weekStatus"?(requested?currentWeek():null):v.field==="monthStatus"?(requested?currentMonth():null):requested,fromValue=task[field]??null;db.aiChanges.push({id:uid(),taskId:task.id,field,fromValue,toValue,status:"pending",createdAt:now(),requestId});if(requestId)db.importHistory.push({requestId,receivedAt:now()});added++}await persist();renderAll();return {received:added}}
window.SimpleStepBridge={receiveAITasks,receiveAIChanges};

// Expired markers are removed from the existing record instead of creating replacements.
function reconcilePeriodStatuses(){for(const task of db.tasks){const changes={};if(task.todayDate&&task.todayDate!==currentDay())changes.todayDate=null;if(task.weekStatusKey&&task.weekStatusKey!==currentWeek())changes.weekStatusKey=null;if(task.monthStatusKey&&task.monthStatusKey!==currentMonth())changes.monthStatusKey=null;if(Object.keys(changes).length)Data.updateTask(task,changes,"system")}}
function shiftReview(days){const d=new Date(activeDate+"T12:00:00");d.setDate(d.getDate()+days);activeDate=dateKey(d);$("#reviewDate").value=activeDate;renderReview()}
function shiftMonth(days){const [y,m]=calendarMonth.split("-").map(Number),d=new Date(y,m-1+days,1);calendarMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;activeDate=calendarMonth+"-01";$("#reviewDate").value=activeDate;renderReview()}
function openTaskEditor(taskId){
 const task=db.tasks.find(item=>item.id===taskId);if(!task)return;
 $("#editTaskId").value=task.id;$("#editTaskTitle").value=task.title;$("#editTaskDescription").value=task.description||"";$("#editTaskStatus").value=task.status;$("#editTaskCompletedDate").value=taskDate(task)||"";$("#editTaskToday").checked=task.todayDate===currentDay();$("#editTaskWeek").checked=isThisWeek(task);$("#editTaskMonth").checked=isThisMonth(task);$("#editTaskStartDate").value=task.startDate||"";$("#editTaskDueDate").value=task.dueDate||"";$("#editTaskCategory").innerHTML=options("categories",task.categoryId);$("#editTaskProject").innerHTML=options("projects",task.projectId);$("#editTaskPriority").value=task.priority||"none";$("#editTaskEstimate").value=task.estimateMinutes||"";$("#editTaskCreatedAt").textContent="登録日："+new Date(task.createdAt).toLocaleString("ja-JP");$("#editTaskRecordMeta").textContent=`ID: ${task.id} ・ 更新 ${new Date(task.updatedAt).toLocaleString("ja-JP")} ・ version ${task.version}`;$("#taskEditor").showModal()
}
function updateRecurringFields(){
 const frequency=$("#editRecurringFrequency").value;
 $("#recurringWeekdays").hidden=frequency!=="weekly";$("#recurringMonthDay").hidden=frequency!=="monthly";$("#recurringIntervalField").hidden=!["weekly","interval"].includes(frequency)
}
function openRecurringEditor(ruleId=""){
 const rule=db.recurringRules.find(item=>item.id===ruleId);
 $("#editRecurringId").value=rule?.id||"";$("#editRecurringTitle").value=rule?.title||"";$("#editRecurringFrequency").value=rule?.frequency||"daily";$("#editRecurringInterval").value=rule?.interval||1;$("#editRecurringDayOfMonth").value=rule?.dayOfMonth||1;$("#editRecurringStartDate").value=rule?.startDate||dateKey();$("#editRecurringEndDate").value=rule?.endDate||"";$$('#recurringWeekdays input').forEach(input=>input.checked=(rule?.daysOfWeek||[]).includes(Number(input.value)));updateRecurringFields();$("#recurringEditor").showModal()
}
function setupEvents(){
document.body.addEventListener("click",async e=>{if(e.target.dataset.action!=="delete-theme")return;const item=db.themes.find(t=>t.id===e.target.dataset.id);if(!item)return;item.deletedAt=now();item.active=false;item.endedAt=item.endedAt||item.deletedAt;await persist();renderAll();e.stopImmediatePropagation()});
$$(".nav-button").forEach(b=>b.onclick=()=>{$$(".nav-button,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.page).classList.add("active");$("#mainNav").classList.remove("open")});$("#menuButton").onclick=()=>$("#mainNav").classList.toggle("open");
$("#taskEditorForm").onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==="cancel"){$("#taskEditor").close();return}const task=db.tasks.find(item=>item.id===$("#editTaskId").value);if(!task)return;const estimate=Number($("#editTaskEstimate").value),status=$("#editTaskStatus").value,completedDate=$("#editTaskCompletedDate").value;Data.updateTask(task,{title:$("#editTaskTitle").value.trim(),description:$("#editTaskDescription").value.trim(),status,todayDate:$("#editTaskToday").checked&&status==="open"?currentDay():null,weekStatusKey:$("#editTaskWeek").checked?currentWeek():null,monthStatusKey:$("#editTaskMonth").checked?currentMonth():null,startDate:$("#editTaskStartDate").value||null,dueDate:$("#editTaskDueDate").value||null,categoryId:$("#editTaskCategory").value,projectId:$("#editTaskProject").value,priority:$("#editTaskPriority").value,estimateMinutes:Number.isInteger(estimate)&&estimate>0?estimate:null,completedAt:status==="done"?(completedDate||currentDay())+"T12:00:00.000Z":null},"user");await persist();$("#taskEditor").close();renderAll()};
$("#addRecurringRule").onclick=()=>openRecurringEditor();$("#editRecurringFrequency").onchange=updateRecurringFields;
$("#recurringEditorForm").onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==="cancel"){ $("#recurringEditor").close();return}const ruleId=$("#editRecurringId").value,existing=db.recurringRules.find(item=>item.id===ruleId),value={...(existing||{}),id:existing?.id||uid(),title:$("#editRecurringTitle").value.trim(),frequency:$("#editRecurringFrequency").value,interval:Number($("#editRecurringInterval").value)||1,daysOfWeek:$$('#recurringWeekdays input:checked').map(input=>Number(input.value)),dayOfMonth:Number($("#editRecurringDayOfMonth").value)||1,startDate:$("#editRecurringStartDate").value,endDate:$("#editRecurringEndDate").value||null,active:existing?.active!==false,updatedAt:now(),updatedBy:"user",version:(existing?.version||0)+1};const normalized=Data.normalizeRecurringRule(value);if(existing)Object.assign(existing,normalized);else db.recurringRules.push(normalized);Data.generateDueTasks(db,dateKey());await persist();$("#recurringEditor").close();renderAll()};
$("#taskForm").onsubmit=async e=>{e.preventDefault();await addTask({title:$("#taskTitle").value});e.target.reset();renderAll()};$("#journalForm").onsubmit=async e=>{e.preventDefault();db.journals.push({id:uid(),type:"journal",text:$("#journalText").value.trim(),entryDate:$("#journalDate").value,themeId:"",createdAt:now(),updatedAt:now(),deletedAt:null,source:"manual"});await persist();$("#journalText").value="";renderAll()};$("#journalDate").onchange=renderJournals;$("#themeComposers").onsubmit=async e=>{e.preventDefault();const form=e.target.closest("[data-theme-id]"),text=form?.querySelector("textarea").value.trim();if(!form||!text)return;db.journals.push({id:uid(),type:"journal",text,entryDate:$("#journalDate").value,themeId:form.dataset.themeId,createdAt:now(),updatedAt:now(),deletedAt:null,source:"manual"});await persist();renderAll()};
$("#previousDay").onclick=()=>shiftReview(-1);$("#nextDay").onclick=()=>shiftReview(1);$("#previousMonth").onclick=()=>shiftMonth(-1);$("#nextMonth").onclick=()=>shiftMonth(1);$("#reviewDate").onchange=()=>{activeDate=$("#reviewDate").value;renderReview()};$("#reviewThemeFilter").onchange=renderReview;$("#reviewCalendar").onclick=e=>{const key=e.target.closest("[data-date]")?.dataset.date;if(key){activeDate=key;$("#reviewDate").value=key;renderReview()}};
for(const kind of ["category","project"])$("#"+kind+"Form").onsubmit=async e=>{e.preventDefault();const input=$("#"+kind+"Name");ensureName(kind==="category"?"categories":"projects",input.value);input.value="";await persist();renderAll()};$("#themeForm").onsubmit=async e=>{e.preventDefault();const input=$("#themeName"),name=input.value.trim();if(name&&!db.themes.some(t=>isLive(t)&&t.name.toLowerCase()===name.toLowerCase()))db.themes.push({id:uid(),name,active:true,createdAt:now(),endedAt:null,deletedAt:null});input.value="";await persist();renderAll()};
$("#classificationTasks").onchange=async e=>{const row=e.target.closest("[data-task-id]"),task=db.tasks.find(t=>t.id===row?.dataset.taskId);if(task&&e.target.dataset.field){Data.updateTask(task,{[e.target.dataset.field]:e.target.value},"user");await persist();renderAll()}};
$("#weekStartsOn").onchange=async e=>{db.settings.weekStartsOn=Number(e.target.value);reconcilePeriodStatuses();await persist();renderAll()};
$("#dayRolloverTime").onchange=async e=>{db.settings.dayRolloverTime=e.target.value;reconcilePeriodStatuses();lastToday=currentDay();await persist();renderAll()};
document.body.addEventListener("click",async e=>{const a=e.target.dataset.action;if(!a)return;if(a==="edit-task"){openTaskEditor(e.target.closest("[data-task-id]")?.dataset.taskId);return}if(a==="edit-recurring"){openRecurringEditor(e.target.closest("[data-rule-id]")?.dataset.ruleId);return}if(a==="toggle-recurring"){const rule=db.recurringRules.find(item=>item.id===e.target.closest("[data-rule-id]")?.dataset.ruleId);if(rule){rule.active=!rule.active;rule.updatedAt=now();rule.updatedBy="user";rule.version=(rule.version||1)+1}}if(a==="menu"){const p=e.target.nextElementSibling;$$(".menu-panel").forEach(x=>{if(x!==p)x.hidden=true});p.hidden=!p.hidden;return}if(["star","complete","delete","change-date"].includes(a))return actTask(e.target,a);if(a==="delete-journal"){const j=db.journals.find(x=>x.id===e.target.closest("[data-journal-id]")?.dataset.journalId);if(j)j.deletedAt=now()}if(a==="approve-pending"||a==="reject-pending"){const t=db.tasks.find(x=>x.id===e.target.closest("[data-task-id]")?.dataset.taskId);if(t)a==="approve-pending"?Data.updateTask(t,{approvalStatus:"approved"},"user"):Data.updateTask(t,{deletedAt:now()},"user")}if(a==="approve-change"||a==="reject-change"){const c=db.aiChanges.find(x=>x.id===e.target.closest("[data-change-id]")?.dataset.changeId);if(c){if(a==="approve-change"){const t=db.tasks.find(x=>x.id===c.taskId);if(t)Data.updateTask(t,{[c.field]:c.toValue},"ai")}c.status=a==="approve-change"?"approved":"rejected"}}if(a==="rename-class"){const item=db[e.target.dataset.kind].find(x=>x.id===e.target.dataset.id),value=prompt("新しい名前",item?.name);if(item&&value?.trim())item.name=value.trim()}if(a==="delete-class"){const kind=e.target.dataset.kind,id=e.target.dataset.id,item=db[kind].find(x=>x.id===id);if(item){item.deletedAt=now();const field=kind==="categories"?"categoryId":"projectId";db.tasks.forEach(t=>{if(t[field]===id)Data.updateTask(t,{[field]:""},"user")})}}if(a==="rename-theme"){const item=db.themes.find(t=>t.id===e.target.dataset.id),value=prompt("新しいテーマ名",item?.name);if(item&&value?.trim())item.name=value.trim()}if(a==="toggle-theme"){const item=db.themes.find(t=>t.id===e.target.dataset.id);if(item){item.active=!item.active;item.endedAt=item.active?null:now()}}if(a==="restore"||a==="purge"){const row=e.target.closest("[data-kind]"),list=row.dataset.kind==="task"?db.tasks:db.journals,index=list.findIndex(x=>x.id===row.dataset.id);if(a==="restore")list[index].deletedAt=null;else if(confirm("完全に削除しますか？"))list.splice(index,1)}await persist();renderAll()});
$("#approveAll").onclick=async()=>{db.tasks.filter(t=>isLive(t)&&t.approvalStatus==="pending").forEach(t=>Data.updateTask(t,{approvalStatus:"approved"},"user"));db.aiChanges.filter(c=>c.status==="pending").forEach(c=>{const t=db.tasks.find(x=>x.id===c.taskId);if(t)Data.updateTask(t,{[c.field]:c.toValue},"ai");c.status="approved"});await persist();renderAll()};
$("#exportBackup").onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="simple-step-v2-"+dateKey()+".json";a.click();URL.revokeObjectURL(a.href)};$("#importBackup").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const value=Data.migrate(JSON.parse(await f.text()));if(!confirm("現在のVer.2データを、バックアップの内容に置き換えますか？"))return;db=value;await persist();renderAll()}catch{alert("有効なバックアップではありません。")}e.target.value=""}
}
async function initialize(){db=await Data.repository.load();lastToday=currentDay();activeDate=lastToday;calendarMonth=activeDate.slice(0,7);reconcilePeriodStatuses();Data.generateDueTasks(db,lastToday);await persist();$("#journalDate").value=lastToday;$("#reviewDate").value=activeDate;setupEvents();renderAll();if(localStorage.getItem(LEGACY_KEY)&&!localStorage.getItem(Data.STORAGE_KEY+"-legacy-noted"))localStorage.setItem(Data.STORAGE_KEY+"-legacy-noted",now());setInterval(async()=>{const day=currentDay();if(day!==lastToday){lastToday=day;reconcilePeriodStatuses();Data.generateDueTasks(db,lastToday);await persist();renderAll()}},60000)}
initialize().catch(err=>{console.error(err);alert("データの読み込みに失敗しました。")});
